---
applications:
  - name: cockroachdb-app-sb
    memory: 1G
    instances: 1
    buildpack: java_buildpack_offline
    path: ../build/libs/cockroachdb-app-0.0.1-SNAPSHOT.jar
    timeout: 360
    env:
      SPRING_PROFILES_ACTIVE: 'sb'
