CREATE TABLE CLAUTHUSER
(
    ID UUID DEFAULT gen_random_uuid(),
    USERNAME STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    ACTIVE BOOLEAN DEFAULT FALSE,
    USER_ROLE STRING DEFAULT 'USER',
    CONSTRAINT CLAUTHUSER_PK PRIMARY KEY (ID)
);

INSERT INTO CLAUTHUSER (USERNAME, FIRST_NAME, LAST_NAME)
VALUES ('testuser', 'William', 'Wallace');
